# QUESTION 1: TIME TUPLE:
print(" TIME TUPLE IS A MODULE IN PYTHON\n IT USE FOR SHOW TIME OR GET TIME \n IT IS A TUPLE WHICH CONTAIN  TOTAL 9 ATTRIBUTE\n AND THESE ATTRIBUTE ARE \n:- ",
      "1)YEAR(4 DIGITS)\n2)MONTH\n3)DAY\n4)HOUR\n5)MINUTES\n6)SECONDS\n7)DAY OF WEEK\n8)DAY OF YEAR\n9)DST(-1,0,1)")
print("\n BY USING THIS TUPLE WE CAN ALSO CHECK EXECUTION TIME OF ANY FUNCTION OR PROGRAM")